# Generated by Django 5.1.2 on 2024-10-23 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Descripción')),
                ('name_ponent', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Nombre del ponente')),
                ('title_ponent', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Título del ponente')),
                ('place', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Lugar')),
                ('initial_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Día y hora de inicio')),
                ('final_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Día y Hora de Fin')),
                ('seats', models.IntegerField(default=0, verbose_name='Lugares disponibles')),
                ('seats_occupied', models.IntegerField(default=0, verbose_name='Lugares ocupados')),
            ],
        ),
    ]
