# Generated by Django 5.1.2 on 2024-10-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='hour',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora'),
        ),
    ]
