# Generated by Django 5.1.2 on 2024-10-23 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='initial_date',
        ),
        migrations.AddField(
            model_name='workshop',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Día'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='final_hour',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='initial_hour',
            field=models.TimeField(blank=True, default=None, null=True, verbose_name='Hora de inicio'),
        ),
    ]
