# Generated by Django 5.1.2 on 2024-10-23 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_workshop_final_date_remove_workshop_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Día'),
        ),
    ]
