# Generated by Django 5.1.2 on 2024-10-23 22:44

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workshop', '0004_alter_workshop_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastname_mat', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('title', models.CharField(default='Ing.', max_length=50, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastname_mat', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('enrollment', models.CharField(max_length=10, verbose_name='Matrícula')),
                ('folio', models.CharField(default='0000', max_length=10, verbose_name='Folio')),
                ('is_valid', models.BooleanField(default=False)),
                ('career', models.CharField(default='Ingeniería en Sistemas Computacionales', max_length=100, verbose_name='Carrera')),
                ('semester', models.IntegerField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo'), ('Noveno', 'Noveno'), ('Décimo', 'Décimo')], default=1, verbose_name='Cuatrimestre')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='workshop.workshop', verbose_name='Taller')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='participant.professor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
