# Generated by Django 5.1.2 on 2024-10-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
