# Generated by Django 5.1.2 on 2024-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_remove_participant_tutor_delete_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='career',
            field=models.CharField(default='IDGS', max_length=100, verbose_name='Carrera'),
        ),
    ]
