# Generated by Django 5.1.2 on 2024-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_participant_phone_alter_participant_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='participants', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='semester',
            field=models.IntegerField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo'), ('Noveno', 'Noveno'), ('Décimo', 'Décimo')], default='Primero', verbose_name='Cuatrimestre'),
        ),
    ]
