# Generated by Django 5.1.2 on 2024-10-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_participant_photo_alter_participant_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='semester',
            field=models.CharField(choices=[('Primero', 'Primero'), ('Segundo', 'Segundo'), ('Tercero', 'Tercero'), ('Cuarto', 'Cuarto'), ('Quinto', 'Quinto'), ('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo'), ('Noveno', 'Noveno'), ('Décimo', 'Décimo')], default='Primero', max_length=15, verbose_name='Cuatrimestre'),
        ),
    ]
