# Generated by Django 5.1.2 on 2024-10-26 19:38

import participant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_alter_participant_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=participant.models.custom_upload_to, verbose_name='Foto'),
        ),
    ]
