# Generated by Django 5.1.2 on 2024-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_alter_participant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='enrollment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='lastname_mat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido materno'),
        ),
    ]
