# Generated by Django 5.1.2 on 2024-10-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_alter_participant_enrollment_and_more'),
        ('tutor', '0001_initial'),
        ('workshop', '0004_alter_workshop_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tutore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.tutor', verbose_name='Tutor'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop', to='workshop.workshop', verbose_name='Taller'),
        ),
    ]
