# Generated by Django 5.1.2 on 2024-10-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0008_participant_tutore_alter_participant_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='enrollment',
            field=models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='Matrícula'),
        ),
    ]
