# Generated by Django 5.1.2 on 2024-10-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0009_alter_participant_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='folio',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Folio'),
        ),
    ]
