# Generated by Django 5.1.2 on 2024-11-06 22:14

import participant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0011_alter_participant_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='enrollment',
            field=models.CharField(blank=True, default='-', max_length=12, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10, validators=[participant.validators.validate_phone], verbose_name='Teléfono'),
        ),
    ]
